site_name: TwoDo
theme:
  name: material


  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
    

  language: en
  palette:
    scheme: slate

copyright: |
  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">Two Dwo</a>

nav:
  - Início: 'index.md'
  - Documentação:
    - 'Visão Geral do Produto': 'documentacao/visaoGeralProduto.md'
    - 'Visão Geral do Projeto': 'documentacao/visaoGeralProjeto.md'
    - 'Processo de Desenvolvimento de Software': 'documentacao/processoDesenvolvimento.md'
    - 'Lições Aprendidas': 'documentacao/licoesAprendidas.md'
    - 'Referências Bibliográficas': 'documentacao/referenciasBibliograficas.md'
  - Entregas: 
    - 'Unidade 1': 
      - 'Seminário - Processos e Ciclos de Vida': 'entregas/unidade 1/seminario.md'
      - 'Vídeo - Apresentação GitPages': 'entregas/unidade 1/videoApresentacao.md'
    - 'Unidade 2':
    - 'Unidade 3':
    - 'Unidade 4':
  - Backlog do Produto: 
    - 'Requisitos funcionais': 'backlog/index.md'
    - 'Requisitos não-funcionais': 'backlog/nao-funcionais.md'










extra:
  prev_next_buttons: true


markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - toc: {} # adiciona a tabela de conteúdo 
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css